version: "2.0"

services:

  traefik:
    container_name: xnat-traefik
    image: "traefik:latest"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api.insecure # Don't do that in production
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik-data/logs:/var/log
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_dash.rule=Host(`dashboard.localhost`)
      - traefik.http.routers.traefik_dash.entrypoints=web
      - traefik.http.routers.traefik_dash.service=api@internal
      - traefik.http.middlewares.append-slash-to-training.redirectregex.regex=^(.+/training/[^/]+)$$
      - traefik.http.middlewares.append-slash-to-training.redirectregex.replacement=$${1}/

  xnat-web:
    container_name: xnat-web
    build:
      context: ./xnat
      args:
        XNAT_VER: '1.7.5.3'
        SMTP_ENABLED: 'false'
        SMTP_HOSTNAME: fake.fake
        SMTP_PORT:
        SMTP_AUTH:
        SMTP_USERNAME:
        SMTP_PASSWORD:
        XNAT_DATASOURCE_DRIVER: 'org.postgresql.Driver'
        XNAT_DATASOURCE_URL: 'jdbc:postgresql://xnat-db/xnat'
        XNAT_DATASOURCE_USERNAME: 'xnat'
        XNAT_DATASOURCE_PASSWORD: 'xnat'
        XNAT_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQL9Dialect'
        TOMCAT_XNAT_FOLDER: ROOT
        XNAT_ROOT: /data/xnat
        XNAT_HOME: /data/xnat/home
    expose:
      - 8080
    ports:
      - "8104:8104"
      - "8144:8144"
    labels:
      - traefik.http.routers.nginx1.rule=PathPrefix(`/`)
    volumes:
      - ./xnat/server.xml:/usr/local/tomcat/conf/server.xml
      - ./xnat-data/archive:/data/xnat/archive
      - ./xnat-data/build:/data/xnat/build
      - ./xnat-data/logs:/data/xnat/home/logs
      - ./xnat/plugins:/data/xnat/home/plugins
      - ./xnat/webapps:/usr/local/tomcat/webapps
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms128m -Xmx8192m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
      - XNAT_HOME=/data/xnat/home

  xnat-db:
    container_name: xnat-db
    build: ./postgres
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  orthanc:
    container_name: xnat-orthanc
    build:
      context: ./orthanc
      args:
        XNAT_DATASOURCE_DRIVER: 'org.postgresql.Driver'
        XNAT_DATASOURCE_URL: 'jdbc:postgresql://xnat-db/xnat'
        XNAT_DATASOURCE_USERNAME: 'xnat'
        XNAT_DATASOURCE_PASSWORD: 'xnat'
    expose:
      - 8042
    ports:
      - "4242:4242"
      - "8042:8042"
    labels:
      - traefik.http.middlewares.orthanc-stripprefix.stripprefix.prefixes=/pacs
      - traefik.http.routers.orthanc.rule=PathPrefix(`/pacs`)
      - traefik.http.routers.orthanc.middlewares=orthanc-stripprefix@docker 
      - traefik.http.services.orthanc.loadbalancer.server.port=8042
    volumes:
      - ./orthanc-data:/var/lib/orthanc/db
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
    depends_on:
      - xnat-db

volumes:
  postgres-data:
